export const AUTH_CONNECTING = 'AUTH_CONNECTING';
export const AUTH_CONNECTED = 'AUTH_CONNECTED';
export const AUTH_DISCONECTED = 'AUTH_DISCONECTED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_RECEIVE = 'CHANNEL_RECEIVE';
export const CHANNEL_REMOVE = 'CHANNEL_REMOVE';
export const CHANNEL_CHANGE = 'CHANNEL_CHANGE';
export const CHANNEL_LOAD = 'CHANNEL_LOAD';
export const CHANNEL_LOAD_SUCCESS = 'CHANNEL_LOAD_SUCCESS';
export const CHANNEL_LOAD_FAIL = 'CHANNEL_LOAD_FAIL';

export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';

export const USER_ADD = 'USER_ADD';
export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_REMOVE = 'USER_REMOVE';
export const USER_LOAD = 'USER_LOAD';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
