export const AUTH_CREDENTIALS_CONNECTING = 'AUTH_CREDENTIALS_CONNECTING';
export const AUTH_TOKEN_CONNECTING = 'AUTH_TOKEN_CONNECTING';
export const AUTH_CONNECTED = 'AUTH_CONNECTED';
export const AUTH_DISCONECTED = 'AUTH_DISCONECTED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SET_ERR_MSG = 'AUTH_SET_ERR_MSG';

export const REGISTERED_NEW_USER = 'REGISTERED_NEW_USER';
export const REGISTERED_NEW_USER_RELOAD = 'REGISTERED_NEW_USER_RELOAD';

export const CHANNEL_ADD_START = 'CHANNEL_ADD_START';
export const CHANNEL_ADD_SUCCESS = 'CHANNEL_ADD_SUCCESS';
export const CHANNEL_ADD_FAIL = 'CHANNEL_ADD_FAIL';
export const CHANNELS_LOAD_START = 'CHANNELS_LOAD_START';
export const CHANNELS_LOAD_SUCCESS = 'CHANNELS_LOAD_SUCCESS';
export const CHANNELS_LOAD_FAIL = 'CHANNELS_LOAD_FAIL';
export const CHANNEL_MSG_LOAD_START = 'CHANNEL_MSG_LOAD_START';
export const CHANNEL_MSG_LOAD_SUCCESS = 'CHANNEL_MSG_LOAD_SUCCESS';
export const CHANNEL_MSG_LOAD_FAIL = 'CHANNEL_MSG_LOAD_FAIL';
//export const CHANNEL_REMOVE = 'CHANNEL_REMOVE';

export const MESSAGE_ADD_START = 'MESSAGE_ADD_START';
export const MESSAGE_ADD_SUCCESS = 'MESSAGE_ADD_SUCCESS';
export const MESSAGE_ADD_FAIL = 'MESSAGE_ADD_FAIL';
export const MESSAGE_ADD_BULK = 'MESSAGE_ADD_BULK';
export const MESSAGE_READ = 'MESSAGE_READ';
export const MESSAGE_ADD = 'MESSAGE_RECEIVE';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';

export const USER_ADD_START = 'USER_ADD_START';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_FAIL = 'USER_ADD_FAIL';
export const USER_MSG_LOAD_START = 'USER_MSG_LOAD_START';
export const USER_MSG_LOAD_SUCCESS = 'USER_MSG_LOAD_SUCCESS';
export const USER_MSG_LOAD_FAIL = 'USER_MSG_LOAD_FAIL';
export const USERS_LOAD_START = 'USERS_LOAD_START';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';

//****************************** delete
export const USER_ADD = 'USER_ADD';
export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_REMOVE = 'USER_REMOVE';
