export const AUTH_CREDENTIALS_CONNECTING = 'AUTH_CREDENTIALS_CONNECTING';
export const AUTH_TOKEN_CONNECTING = 'AUTH_TOKEN_CONNECTING';
export const AUTH_CONNECTED = 'AUTH_CONNECTED';
export const AUTH_DISCONECTED = 'AUTH_DISCONECTED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SET_ERR_MSG = 'AUTH_SET_ERR_MSG';

export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_RECEIVE = 'CHANNEL_RECEIVE';
export const CHANNEL_REMOVE = 'CHANNEL_REMOVE';
export const CHANNEL_CHANGE = 'CHANNEL_CHANGE';
export const CHANNEL_LOAD = 'CHANNEL_LOAD';
export const CHANNEL_LOAD_SUCCESS = 'CHANNEL_LOAD_SUCCESS';
export const CHANNEL_LOAD_FAIL = 'CHANNEL_LOAD_FAIL';

export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_RECEIVE = 'MESSAGE_RECEIVE';

export const USER_ADD = 'USER_ADD';
export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_REMOVE = 'USER_REMOVE';
export const USERS_LOAD_START = 'USERS_LOAD_START';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';
